Some changes
LolGleb/TestPhpProj pull request #1
Opened 2024-04-03 12:04 UTC by LolGleb

2024-04-03 12:33 UTC, FoxGleb commented
Not bad, not bad

2024-04-03 12:50 UTC, FoxGleb commented
Yo🙏
Nice👍

2024-04-03 13:10 UTC, FoxGleb commented
lkmlknj jk   jk  f 
 efw
 df 
sd 
f s
f
 ewsef
 sd
 f
 sd
f s
d f
 
sdf 
sdf
 sd
 fds fd

2024-04-03 13:12 UTC, FoxGleb commented on tests/SomeClassTest.php
> +require_once 'vendor/autoload.php';
Not sure if that really necessary

2024-04-03 13:14 UTC, FoxGleb commented on vendor/bin/php-parse
> -#!/usr/bin/env php
WHYyyyyyyyy?

2024-04-03 13:16 UTC, LolGleb commented on tests/SomeClassTest.php
> +require_once 'vendor/autoload.php';
IT IS

2024-04-03 13:19 UTC, LolGleb commented on vendor/bin/php-parse
> -#!/usr/bin/env php
Chikibamboni?

2024-04-03 13:20 UTC, LolGleb commented on vendor/bin/php-parse.bat
> -@ECHO OFF
Yo

2024-04-03 13:20 UTC, LolGleb commented on vendor/bin/php-parse.bat
> -@ECHO OFF
d

2024-04-03 16:00 UTC, LolGleb commented on tests/SomeClassTest.php
> +require_once 'vendor/autoload.php';
Just a comment

2024-04-03 16:39 UTC, LolGleb commented on vendor/bin/php-parse.bat
> -setlocal DISABLEDELAYEDEXPANSION
Hop hey la la ley

2024-04-03 16:41 UTC, LolGleb commented on vendor/bin/php-parse.bat
> -@ECHO OFF
hop hey la la ley

2024-04-03 16:44 UTC, LolGleb commented on vendor/bin/phpunit
> -#!/usr/bin/env php
cho

2024-04-03 16:44 UTC, LolGleb commented on vendor/bin/php-parse.bat
> -@ECHO OFF
d

2024-04-04 08:07 UTC, FoxGleb requested changes
Change something

2024-04-04 08:08 UTC, LolGleb commented
But I don't want to!

2024-04-04 08:09 UTC, FoxGleb commented
Okaaaay

2024-04-04 08:09 UTC, FoxGleb approved these changes
All is fine

2024-04-04 08:09 UTC, merged